ERROR 2025-04-14 10:18:46,075 log Internal Server Error: /dairy/customers/251/
Traceback (most recent call last):
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\views\generic\detail.py", line 113, in get
    context = self.get_context_data(object=self.object)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\dairy_app\views.py", line 319, in get_context_data
    start_date = datetime.date(selected_year, selected_month, 1)
                 ^^^^^^^^
NameError: name 'datetime' is not defined. Did you forget to import 'datetime'
ERROR 2025-04-14 10:18:46,084 basehttp "GET /dairy/customers/251/ HTTP/1.1" 500 93904
ERROR 2025-04-14 10:19:09,930 log Internal Server Error: /dairy/customers/251/
Traceback (most recent call last):
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\views\generic\detail.py", line 113, in get
    context = self.get_context_data(object=self.object)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\dairy_app\views.py", line 319, in get_context_data
    start_date = datetime.date(selected_year, selected_month, 1)
                 ^^^^^^^^
NameError: name 'datetime' is not defined. Did you forget to import 'datetime'
ERROR 2025-04-14 10:19:09,936 basehttp "GET /dairy/customers/251/ HTTP/1.1" 500 94041
ERROR 2025-04-14 10:19:13,426 log Internal Server Error: /dairy/customers/251/
Traceback (most recent call last):
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\views\generic\detail.py", line 113, in get
    context = self.get_context_data(object=self.object)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\dairy_app\views.py", line 319, in get_context_data
    start_date = datetime.date(selected_year, selected_month, 1)
                 ^^^^^^^^
NameError: name 'datetime' is not defined. Did you forget to import 'datetime'
ERROR 2025-04-14 10:19:13,433 basehttp "GET /dairy/customers/251/ HTTP/1.1" 500 93904
ERROR 2025-04-14 10:20:45,827 log Internal Server Error: /dairy/customers/311/
Traceback (most recent call last):
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\views\generic\detail.py", line 113, in get
    context = self.get_context_data(object=self.object)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\dairy_app\views.py", line 319, in get_context_data
    start_date = datetime.date(selected_year, selected_month, 1)
                 ^^^^^^^^
NameError: name 'datetime' is not defined. Did you forget to import 'datetime'
ERROR 2025-04-14 10:20:45,834 basehttp "GET /dairy/customers/311/ HTTP/1.1" 500 93881
ERROR 2025-04-14 10:22:05,569 log Internal Server Error: /dairy/customers/251/
Traceback (most recent call last):
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\smartif.py", line 180, in translate_token
    op = OPERATORS[token]
         ~~~~~~~~~^^^^^^^
KeyError: 'data.milk_data|get_item:milk_type.name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\defaulttags.py", line 962, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\defaulttags.py", line 862, in do_for
    nodelist_loop = parser.parse(
                    ^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\defaulttags.py", line 862, in do_for
    nodelist_loop = parser.parse(
                    ^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\defaulttags.py", line 961, in do_if
    condition = TemplateIfParser(parser, bits).parse()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\defaulttags.py", line 894, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\smartif.py", line 171, in __init__
    mapped_tokens.append(self.translate_token(token))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\smartif.py", line 182, in translate_token
    return self.create_var(token)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\defaulttags.py", line 897, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\base.py", line 609, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\base.py", line 705, in __init__
    filter_func = parser.find_filter(filter_name)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\base.py", line 615, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
django.template.exceptions.TemplateSyntaxError: Invalid filter: 'get_item'
ERROR 2025-04-14 10:22:05,588 basehttp "GET /dairy/customers/251/ HTTP/1.1" 500 410819
ERROR 2025-04-14 10:22:48,707 log Internal Server Error: /dairy/customers/251/
Traceback (most recent call last):
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\smartif.py", line 180, in translate_token
    op = OPERATORS[token]
         ~~~~~~~~~^^^^^^^
KeyError: 'data.milk_data|get_item:milk_type.name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\defaulttags.py", line 962, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\defaulttags.py", line 862, in do_for
    nodelist_loop = parser.parse(
                    ^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\defaulttags.py", line 862, in do_for
    nodelist_loop = parser.parse(
                    ^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\defaulttags.py", line 961, in do_if
    condition = TemplateIfParser(parser, bits).parse()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\defaulttags.py", line 894, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\smartif.py", line 171, in __init__
    mapped_tokens.append(self.translate_token(token))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\smartif.py", line 182, in translate_token
    return self.create_var(token)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\defaulttags.py", line 897, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\base.py", line 609, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\base.py", line 705, in __init__
    filter_func = parser.find_filter(filter_name)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\base.py", line 615, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
django.template.exceptions.TemplateSyntaxError: Invalid filter: 'get_item'
ERROR 2025-04-14 10:22:48,717 basehttp "GET /dairy/customers/251/ HTTP/1.1" 500 410819
ERROR 2025-04-14 10:23:12,206 log Internal Server Error: /dairy/customers/251/
Traceback (most recent call last):
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\smartif.py", line 180, in translate_token
    op = OPERATORS[token]
         ~~~~~~~~~^^^^^^^
KeyError: 'data.milk_data|get_item:milk_type.name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\defaulttags.py", line 962, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\defaulttags.py", line 862, in do_for
    nodelist_loop = parser.parse(
                    ^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\defaulttags.py", line 862, in do_for
    nodelist_loop = parser.parse(
                    ^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\defaulttags.py", line 961, in do_if
    condition = TemplateIfParser(parser, bits).parse()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\defaulttags.py", line 894, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\smartif.py", line 171, in __init__
    mapped_tokens.append(self.translate_token(token))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\smartif.py", line 182, in translate_token
    return self.create_var(token)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\defaulttags.py", line 897, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\base.py", line 609, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\base.py", line 705, in __init__
    filter_func = parser.find_filter(filter_name)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mayur\OneDrive\Documents\dairy_manager\dairy_manager\venv\Lib\site-packages\django\template\base.py", line 615, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
django.template.exceptions.TemplateSyntaxError: Invalid filter: 'get_item'
ERROR 2025-04-14 10:23:12,216 basehttp "GET /dairy/customers/251/ HTTP/1.1" 500 410819
